[2020-11-30 15:20:00,498] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 15:45:38,068] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 15:48:44,262] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/Customers?serverTimezone=UTC Caused by :No suitable driver")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 16:42:50,309] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client Caused by :Client does not support authentication protocol requested by server; consider upgrading MySQL client") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client Caused by :Client does not support authentication protocol requested by server; consider upgrading MySQL client")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client Caused by :Client does not support authentication protocol requested by server; consider upgrading MySQL client")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 16:45:51,335] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client Caused by :Client does not support authentication protocol requested by server; consider upgrading MySQL client") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client Caused by :Client does not support authentication protocol requested by server; consider upgrading MySQL client")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to initialize pool: Client does not support authentication protocol requested by server; consider upgrading MySQL client Caused by :Client does not support authentication protocol requested by server; consider upgrading MySQL client")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 16:50:11,039] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 16:51:22,527] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 16:56:43,666] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'root'@'localhost' Caused by :Access denied for user 'root'@'localhost'")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-11-30 17:03:52,001] SEVERE {b7a.log.crash} - error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'aneesha'@'localhost' (using password: NO) Caused by :Access denied for user 'aneesha'@'localhost' (using password: NO)") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'aneesha'@'localhost' (using password: NO) Caused by :Access denied for user 'aneesha'@'localhost' (using password: NO)")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:562)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("Error in SQL connector configuration: Failed to initialize pool: Access denied for user 'aneesha'@'localhost' (using password: NO) Caused by :Access denied for user 'aneesha'@'localhost' (using password: NO)")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.sql.utils.ErrorGenerator.getSQLApplicationError(ErrorGenerator.java:65)
	at org.ballerinalang.sql.datasource.SQLDatasource.buildDataSource(SQLDatasource.java:242)
	at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:55)
	at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:119)
	at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:112)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:111)
	at org.ballerinalang.sql.utils.ClientUtils.createClient(ClientUtils.java:43)
	at org.ballerinalang.jdbc.NativeImpl.createClient(NativeImpl.java:75)
	at ballerina.java_jdbc.0_5_1.client.createClient(client.bal:147)
	at ballerina.java_jdbc.0_5_1.$value$Client.init(client.bal:44)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at ballerina.java_jdbc.0_5_1.$value$Client.$init$(client.bal:22)
	at ballerina.java_jdbc.0_5_1.$value$Client.call(client.bal)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_1(RESTModule:4)
	at aneesha.RESTModule.0_1_0.RESTModule.$aneesha_RESTModule_0_1_0__init_0(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__init_(RESTModule:0)
	at aneesha.RESTModule.0_1_0.$_init.$moduleInit(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-12-01 12:47:36,296] SEVERE {b7a.log.crash} - error("failed to start server connector '0.0.0.0:9090': Address already in use") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:572)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:564)
	at org.ballerinalang.net.http.serviceendpoint.Start.startServerConnector(Start.java:63)
	at org.ballerinalang.net.http.serviceendpoint.Start.start(Start.java:41)
	at ballerina.http.1_0_1.service_endpoint.externStart(service_endpoint.bal:148)
	at ballerina.http.1_0_1.$value$Listener.startEndpoint(service_endpoint.bal:119)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at ballerina.http.1_0_1.$value$Listener.__start(service_endpoint.bal:40)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at aneesha.RESTModuleDB.0_1_0.$_init.$aneesha_RESTModuleDB_0_1_0__start_(RESTModuleDB:20)
	at aneesha.RESTModuleDB.0_1_0.$_init.$moduleStart(RESTModuleDB)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-12-01 12:47:38,880] SEVERE {b7a.log.crash} - error("failed to start server connector '0.0.0.0:9090': Address already in use") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:572)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:564)
	at org.ballerinalang.net.http.serviceendpoint.Start.startServerConnector(Start.java:63)
	at org.ballerinalang.net.http.serviceendpoint.Start.start(Start.java:41)
	at ballerina.http.1_0_1.service_endpoint.externStart(service_endpoint.bal:148)
	at ballerina.http.1_0_1.$value$Listener.startEndpoint(service_endpoint.bal:119)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at ballerina.http.1_0_1.$value$Listener.__start(service_endpoint.bal:40)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__start_(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$moduleStart(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2020-12-01 13:02:06,446] SEVERE {b7a.log.crash} - Test [testGetCustomer] depends on function [testAddCustomer], but it couldn't be found. 
io.ballerina.runtime.util.exceptions.BallerinaException: Test [testGetCustomer] depends on function [testAddCustomer], but it couldn't be found.
	at org.ballerinalang.test.runtime.BTestRunner.checkCyclicDependencies(BTestRunner.java:177)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:103)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
 
[2020-12-01 13:02:08,581] SEVERE {b7a.log.crash} - error("failed to start server connector '0.0.0.0:9090': Address already in use") 
io.ballerina.runtime.util.exceptions.BallerinaException: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:122)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:56)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:572)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:74)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:60)
	at org.ballerinalang.test.runtime.Main.main(Main.java:52)
Caused by: error("failed to start server connector '0.0.0.0:9090': Address already in use")
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:154)
	at io.ballerina.runtime.api.ErrorCreator.createDistinctError(ErrorCreator.java:138)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:564)
	at org.ballerinalang.net.http.serviceendpoint.Start.startServerConnector(Start.java:63)
	at org.ballerinalang.net.http.serviceendpoint.Start.start(Start.java:41)
	at ballerina.http.1_0_1.service_endpoint.externStart(service_endpoint.bal:148)
	at ballerina.http.1_0_1.$value$Listener.startEndpoint(service_endpoint.bal:119)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at ballerina.http.1_0_1.$value$Listener.__start(service_endpoint.bal:40)
	at ballerina.http.1_0_1.$value$Listener.call(service_endpoint.bal)
	at aneesha.RESTModule.0_1_0.$_init.$aneesha_RESTModule_0_1_0__start_(RESTModule:5)
	at aneesha.RESTModule.0_1_0.$_init.$moduleStart(RESTModule)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
	at io.ballerina.runtime.scheduling.SchedulerItem.execute(Scheduler.java:501)
	at io.ballerina.runtime.scheduling.Scheduler.run(Scheduler.java:277)
	at io.ballerina.runtime.scheduling.Scheduler.runSafely(Scheduler.java:245)
	at java.base/java.lang.Thread.run(Unknown Source)
 
